### ISSUE TITLE
Option to enable returning a path only if history.pushState is a thing

### ISSUE THREAD

**Issue by HenrikJoreteg** [lukekarrys/local-links#9]
So in the case of IE9 for example. If you're using a super simple routing approach like, for example that in: https://github.com/HenrikJoreteg/feather-app

There's a potential issue with `getLocalPathname` in that it will return a path, despite not actually being able to do a `pushState` which is what it will attempt to do if there's a matching path.

This made me wonder if perhaps there shouldn't be an option (or maybe even be the default) that if `history.pushState` doesn't exist, it just always returns `null`. This would cause internal links to do a full page refresh, which would be slower, but still produce the right result. I don't know if this really matters, however because if pushState fails, the app would still update the view just not update the URL which may be a better fallback???

Do what you will with this, but it was just a thought I figured may be worth raising.

**Comment by lukekarrys** [comment]
I see why you'd want this for the feather-app example, but it still doesn't feel like the right place to put that is in this lib.

I see `history.pushState` mostly as an implementation detail of an app, so I think it's best left up to a decision there.
